apiVersion: v1
kind: Service       
metadata:
  name: controllerdemo
  namespace: controllerdemo
spec:
  type: NodePort    
  ports:
  - nodePort: 31606
    port: 80        
    protocol: TCP   
    targetPort: 80
  selector:         
    app: controllerdemo